"""add title index to tickets

Revision ID: 0187bc0490f4
Revises: 3fadbfd951b0
Create Date: 2026-07-04 16:12:39.242119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0187bc0490f4'
down_revision: Union[str, Sequence[str], None] = '3fadbfd951b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tickets_title'), 'tickets', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_title'), table_name='tickets')
    # ### end Alembic commands ###
